# Generated by Django 5.0.6 on 2024-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
