# Generated by Django 5.0.6 on 2024-06-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_folder_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='deck.folder')),
            ],
        ),
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='deck.table')),
            ],
        ),
    ]
