# Generated by Django 5.0.6 on 2024-06-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_table_tablecell'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_local_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
